# Generated by Django 5.2.7 on 2025-11-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proveedor_telefono_alter_proveedor_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
