# Generated by Django 5.2.7 on 2025-11-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
